definitions:
  handlers.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  handlers.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  models.Reminder:
    properties:
      created_at:
        type: string
      id:
        type: integer
      is_sent:
        type: boolean
      message:
        type: string
      send_at:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /reminders:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all reminders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Reminder'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Get all reminders
      tags:
      - reminders
    post:
      consumes:
      - application/json
      description: Create a new reminder with the provided details
      parameters:
      - description: Reminder object
        in: body
        name: reminder
        required: true
        schema:
          $ref: '#/definitions/models.Reminder'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Reminder'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Create a new reminder
      tags:
      - reminders
  /reminders/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a reminder by ID if it has not been sent
      parameters:
      - description: Reminder ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Delete a reminder
      tags:
      - reminders
    put:
      consumes:
      - application/json
      description: Update the reminder with the given ID
      parameters:
      - description: Reminder ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated reminder object
        in: body
        name: reminder
        required: true
        schema:
          $ref: '#/definitions/models.Reminder'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Reminder'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Update an existing reminder
      tags:
      - reminders
  /reminders/{user_id}:
    get:
      consumes:
      - application/json
      description: Retrieve all reminders for a specific user
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Reminder'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Get reminders by user ID
      tags:
      - reminders
swagger: "2.0"
